#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
app_login:
  path: /login
  controller: App\Controller\SecurityController::login

home:
  path: /home
  controller: App\Controller\HomeController::home

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

api_login_check:
  path: /api/login_check