#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
api_login_check:
  path: /api/login_check